# permissions for end users to edit blockdevices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: blockdevice-editor-role
rules:
- apiGroups:
  - suxueit.com
  resources:
  - blockdevices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - suxueit.com
  resources:
  - blockdevices/status
  verbs:
  - get
